spring.application.name=spring-boot-chicken-management

# --- Active Profile ---
# This tells Spring Boot to also load properties from application-local.properties
spring.profiles.active=local

# --- PostgreSQL Datasource Configuration ---
# The sensitive username and password are now in the local file
spring.datasource.url=jdbc:postgresql://localhost:5432/chicken_management
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA (Java Persistence API) Configuration ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# --- Email Sender Configuration ---
# The sensitive username and password are now in the local file
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- Flyway Configuration ---
# Initialize Flyway on an existing database
spring.flyway.baseline-on-migrate=true
